{% set name = "reportlab" %}
{% set version = "4.0.0" %}
{% set sha256 = "3ea3b2954cb434b024dac61e9f270f2a4c0f9e0cc8b2cf2e310273307b2ba05c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - pillow >=9
    - rlpycairo >=0.2.0
    - freetype-py >=2.3
  run:
    - python
    - pillow >=9
    - rlpycairo >=0.2.0
    - freetype-py >=2.3

test:
  imports:
    - reportlab
    - reportlab.graphics.charts
    - reportlab.graphics.samples
    - reportlab.graphics.widgets
    - reportlab.graphics.barcode
    - reportlab.graphics
    - reportlab.lib
    - reportlab.pdfbase
    - reportlab.pdfgen
    - reportlab.platypus

about:
  home: http://www.reportlab.com/opensource/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Open-source engine for creating complex, data-driven PDF documents and custom vector graphics
  doc_url: http://www.reportlab.com/documentation/

extra:
  recipe-maintainers:
    - bkpoon
    - mcs07
